name: Build NAVARA-RP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Compile Pawn gamemode
        uses: knryuu/pawn-compiler-action@v1
        with:
          compiler: pawno
          source: gamemodes/new.pwn
          includes: pawno/include
